#!/usr/bin/env python3

import csv
import os
import sys
import tempfile

import tldextract

def spew_file(pathname, content):
    try:
        os.makedirs(os.path.split(pathname)[0])
    except FileExistsError:
        return
    with tempfile.NamedTemporaryFile(dir=os.path.dirname(pathname), mode='w+',
                                     delete=False, encoding='utf-8') as scratch:
        scratch.write(content)
    os.replace(scratch.name, pathname)


if __name__ == '__main__':
    for line in csv.reader(sys.stdin):
        (name, oo_url, crap) = line

        tld = tldextract.extract(oo_url)
        domain = '.'.join([tld.domain, tld.suffix])

        entry = '''# %s

Name: %s

Domain: %s

Opt_out_url: %s
''' % (name, name, domain, oo_url)

        path = 'domain/%s/index.md' % domain
        try:
            spew_file(path, entry)
        except:
            pass

# vim: autoindent textwidth=100 tabstop=4 shiftwidth=4 expandtab softtabstop=4 filetype=python

