#!/usr/bin/env python3

import json
import os
import sys
import tempfile

import clearbit
import tldextract


def spew_file(pathname, content):
    try:
        os.makedirs(os.path.split(pathname)[0])
    except FileExistsError:
        return
    with tempfile.NamedTemporaryFile(dir=os.path.dirname(pathname), mode='w+',
                                     delete=False, encoding='utf-8') as scratch:
        scratch.write(content)
    os.replace(scratch.name, pathname)

def list_entry(domain, name):
    return '''---
domain: %s
company-name: "%s"
category: list-entry
layout: list-entry
list: adobe-cloud-device-co-op
list-name: "Adobe Experience Cloud Device Co-Op"
list-data-url: https://cross-device-privacy.adobe.com/data/participating-companies.json
list-home: https://cross-device-privacy.adobe.com/
---

This is an automatically populated list entry. See [Adobe Experience Cloud Cross-Device Privacy Tool](https://cross-device-privacy.adobe.com/) for more info on this list.

''' % (domain, name)


if __name__ == '__main__':
    key = os.environ.get('CLEARBIT_SECRET')
    clearbit.key = key
    data = json.loads(sys.stdin.read())
    for entry in data['companies']:
        company_name = entry['name']
        domain = company_name
        result = clearbit.NameToDomain.find(name=entry['name'])
        print(result)
        try:
            domain = result['domain']
            company_name = result['name']
        except:
            next
        content = list_entry(domain, company_name)
        pathname = '_list/adobe-cloud-device-co-op/%s/index.md' % domain
        spew_file(pathname, content)

# vim: autoindent textwidth=100 tabstop=4 shiftwidth=4 expandtab softtabstop=4 filetype=python
#
