#!/usr/bin/env python3

import json
import os
import sys
import tempfile

def spew_file(pathname, content):
    try:
        os.makedirs(os.path.split(pathname)[0])
    except FileExistsError:
        return
    with tempfile.NamedTemporaryFile(dir=os.path.dirname(pathname), mode='w+',
                                     delete=False, encoding='utf-8') as scratch:
        scratch.write(content)
    os.replace(scratch.name, pathname)

def list_entry(domain):
    return '''---
domain: %s
category: list-entry
layout: list-entry
list: acceptable-ads
list-name: "Adblock Plus Acceptable Ads"
list-data-url: https://hg.adblockplus.org/exceptionrules/raw-file/tip/exceptionrules/exceptionrules.txt
list-home: https://acceptableads.com/
---

This is an automatically populated list entry.  See [FTC Urged To Investigate AdBlock Plus Whitelist
01/15/2020](https://www.mediapost.com/publications/article/345686/ftc-urged-to-investigate-adblock-plus-whitelist.html)
for more information on this list.

''' % (domain)

if __name__ == '__main__':
    for domain in sys.stdin.readlines():
        domain.strip()
        content = list_entry(domain)
        pathname = '_list/acceptable-ads/%s/index.md' % domain
        spew_file(pathname, content)

# vim: autoindent textwidth=100 tabstop=4 shiftwidth=4 expandtab softtabstop=4 filetype=python
#
